version: 2
project_name: gcplane

builds:
  - main: .
    binary: gcplane
    ldflags:
      - -s -w -X github.com/dataplanelabs/gcplane/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^feat'
    - title: Bug Fixes
      regexp: '^fix'
    - title: Refactoring
      regexp: '^refactor'
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/dataplanelabs/gcplane:{{ .Version }}"
      - "ghcr.io/dataplanelabs/gcplane:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/dataplanelabs/gcplane"
