apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcplane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gcplane.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8480"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8480
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gcplane.selectorLabels" . | nindent 4 }}
