{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gcplane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gcplane.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gcplane.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
