apiVersion: v1
kind: Service
metadata:
  name: gcplane
  labels:
    app: gcplane
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8480"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8480
      targetPort: http
      protocol: TCP
  selector:
    app: gcplane
